<a href="https://colab.research.google.com/github/imammarzuki/numpy/blob/main/MengenalNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sumber : https://revou.co/panduan-teknis/numpy-python

In [5]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3, 4, 5])

In [7]:
Array_nol = np.zeros(5)

In [8]:
Array_satu = np.ones(5)

In [9]:
Array_dengan_rentang_nilai = np.arange(0, 10, 2)

In [12]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

hasil = arr1 + arr2
print(hasil)

[5 7 9]


In [14]:
arr = np.array([1, 2, 3, 4, 5])

rata_rata = np.mean(arr)
median = np.median(arr)

In [16]:
list_angka = [1, 2, 3, 4, 5]

In [18]:
list_angka

[1, 2, 3, 4, 5]

In [19]:
print(list_angka)

[1, 2, 3, 4, 5]


In [17]:
import numpy as np

arr_angka = np.array(list_angka)
print(arr_angka)

[1 2 3 4 5]


In [20]:
tuple_angka = (6, 7, 8, 9, 10)

In [21]:
arr_tuple = np.array(tuple_angka)
print(arr_tuple)

[ 6  7  8  9 10]


In [22]:
import numpy as np

# Membuat array 2x3 (2 baris, 3 kolom)
array_dua_dimensi = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:")
print(array_dua_dimensi)

Array 2D:
[[1 2 3]
 [4 5 6]]


In [23]:
import numpy as np

arr = np.array([0, np.pi/2, np.pi])
hasil_sin = np.sin(arr)
print(hasil_sin)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [25]:
hasil_cos = np.cos(arr)
print(hasil_cos)

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [26]:
arr2 = np.array([1, 4, 9, 16])
hasil_sqrt = np.sqrt(arr2)
print(hasil_sqrt)

[1. 2. 3. 4.]
